language: ruby
rvm:
        - 2.4.0
addons:
        postgresql '9.6'
notifications:
        email: false
env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install: 
        - sudo apt-get install wget build-essential libc6-dev
        - mkdir fts && cd fts && wget ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.21.tar.gz && tar -xzf freetds-1.00.21.tar.gz && cd freetds-1.00.21 && ./configure --prefix=/usr/local --with-tdsver=7.3 && make &&  sudo make install
        - sudo locale-gen --no-archive es_CO.UTF-8
        - psql -c 'CREATE DATABASE sal7711_pru;' -U postgres
        - bundle install
        - cp db/structure.sql db/structure.sql.conlock
        - sed -e "s/SET lock_timeout = 0;//g" db/structure.sql.conlock >db/structure.sql
        - cp config/database.travis.yml config/database.yml
        - cp config/application.rb.plantilla config/application.rb
        - cp config/routes.rb.plantilla config/routes.rb
        - cp config/initializers/sip.rb.plantilla config/initializers/sip.rb
        - rake db:setup
        - rake sip:indices

